DROP TABLE IF EXISTS catalog.agreement;

CREATE TABLE IF NOT EXISTS catalog.agreement
(
    id INT GENERATED ALWAYS AS IDENTITY,
    name VARCHAR(50) NOT NULL,
    created_at TIME WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIME WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT agreement_pkey PRIMARY KEY (id)
);