DROP TABLE IF EXISTS config.annual_rate;

CREATE TABLE IF NOT EXISTS config.annual_rate
(
  id INT GENERATED ALWAYS AS IDENTITY,
  rate DECIMAL(20,6) NOT NULL,
  period SMALLINT NOT NULL CONSTRAINT validate_period CHECK (period IN (1, 2, 3)),
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);