DROP TABLE IF EXISTS administration.city;

CREATE TABLE IF NOT EXISTS administration.city
(
  id INT GENERATED ALWAYS AS IDENTITY,
  state_id INT NOT NULL,
  name VARCHAR(50) NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT city_pkey PRIMARY KEY (id),
  CONSTRAINT city_state_id_fkey FOREIGN KEY (state_id)
    REFERENCES catalog.state (id)
);